/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Empleado;
import controlador.Planilla;
import controlador.Usuario;
import datos.ControlDAO;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan Rodríguez 8-993-1939
 */
public class frmLobby extends javax.swing.JFrame {

    private String user;
    boolean updateEmpleado;

    /**
     * Creates new form frmLobby
     *
     * @param userLogged
     */
    public frmLobby() {
        initComponents();
    }

    public frmLobby(String userLogged) {
        initComponents();
        this.user = userLogged;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        jPanelEmpleados = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        txtCedulaBuscar = new javax.swing.JTextField();
        btnBuscarEmpleado = new javax.swing.JPanel();
        labelBuscar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblcedula = new javax.swing.JLabel();
        txtCedulaBuscado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSegundoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbAnio = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        cbDia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnGuardar = new javax.swing.JPanel();
        labelGuardarBoton = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JPanel();
        labelNuevoBoton = new javax.swing.JLabel();
        btnEditar = new javax.swing.JPanel();
        labelEditarBoton = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanelCrearUsuario = new javax.swing.JPanel();
        bg1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtUsuarioID = new javax.swing.JTextField();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellidoUsuario = new javax.swing.JTextField();
        txtCedulaUsuario = new javax.swing.JTextField();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        txtDireccionUsuario = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnCrearUsuario = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        cbAnioUsuario = new javax.swing.JComboBox<>();
        cbMesUsuario = new javax.swing.JComboBox<>();
        cbDiaUsuario = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanelPlanilla = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jbteliminar = new javax.swing.JButton();
        jbtadicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblplanilla = new javax.swing.JTable();
        jbtnactuali = new javax.swing.JButton();
        labelfondo = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        labelfondo1 = new javax.swing.JLabel();
        labelfondo2 = new javax.swing.JLabel();
        labelfondo3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmCrearUsuario = new javax.swing.JMenu();
        jmVerEmpleado = new javax.swing.JMenu();
        jmCrearPlanilla = new javax.swing.JMenu();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelPrincipal.setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));

        lblCedula.setBackground(new java.awt.Color(255, 255, 255));
        lblCedula.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblCedula.setText("Ingrese la cédula:");

        txtCedulaBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtCedulaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaBuscarActionPerformed(evt);
            }
        });

        btnBuscarEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscarEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarEmpleadoMouseClicked(evt);
            }
        });

        labelBuscar.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        labelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        labelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBuscar.setText("Buscar");
        labelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnBuscarEmpleadoLayout = new javax.swing.GroupLayout(btnBuscarEmpleado);
        btnBuscarEmpleado.setLayout(btnBuscarEmpleadoLayout);
        btnBuscarEmpleadoLayout.setHorizontalGroup(
            btnBuscarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        btnBuscarEmpleadoLayout.setVerticalGroup(
            btnBuscarEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedulaBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 730, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblcedula.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lblcedula.setText("Cédula");

        txtCedulaBuscado.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtCedulaBuscado.setBorder(null);
        txtCedulaBuscado.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("Primer Nombre");

        txtPrimerNombre.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtPrimerNombre.setBorder(null);
        txtPrimerNombre.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setText("Segundo Nombre");

        txtSegundoNombre.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtSegundoNombre.setBorder(null);
        txtSegundoNombre.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel3.setText("Primer Apellido");

        txtApellido1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtApellido1.setBorder(null);
        txtApellido1.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel4.setText("Segundo Apellido");

        txtApellido2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtApellido2.setBorder(null);
        txtApellido2.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel5.setText("Fecha de nacimiento ");

        cbAnio.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cbAnio.setMaximumRowCount(11);
        cbAnio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        cbAnio.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.black, null));
        cbAnio.setEnabled(false);
        cbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnioActionPerformed(evt);
            }
        });

        cbMes.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cbMes.setMaximumRowCount(13);
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbMes.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));
        cbMes.setEnabled(false);

        cbDia.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        cbDia.setMaximumRowCount(12);
        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbDia.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));
        cbDia.setEnabled(false);
        cbDia.setName("Día"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel6.setText("Dirección");

        txtDireccion.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtDireccion.setBorder(null);
        txtDireccion.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel7.setText("Teléfono");

        txtTelefono.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        txtTelefono.setBorder(null);
        txtTelefono.setEnabled(false);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        btnGuardar.setBackground(new java.awt.Color(0, 0, 0));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar.setEnabled(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        labelGuardarBoton.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        labelGuardarBoton.setForeground(new java.awt.Color(255, 255, 255));
        labelGuardarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGuardarBoton.setText("Guardar");
        labelGuardarBoton.setEnabled(false);
        labelGuardarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelGuardarBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnNuevo.setBackground(new java.awt.Color(0, 0, 0));
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelNuevoBoton.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        labelNuevoBoton.setForeground(new java.awt.Color(255, 255, 255));
        labelNuevoBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNuevoBoton.setText("Nuevo");
        labelNuevoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelNuevoBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnNuevoLayout = new javax.swing.GroupLayout(btnNuevo);
        btnNuevo.setLayout(btnNuevoLayout);
        btnNuevoLayout.setHorizontalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNuevoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );
        btnNuevoLayout.setVerticalGroup(
            btnNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNuevoBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnEditar.setBackground(new java.awt.Color(0, 0, 0));
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.setEnabled(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        labelEditarBoton.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        labelEditarBoton.setForeground(new java.awt.Color(255, 255, 255));
        labelEditarBoton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEditarBoton.setText("Editar");
        labelEditarBoton.setEnabled(false);
        labelEditarBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEditarBotonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnEditarLayout = new javax.swing.GroupLayout(btnEditar);
        btnEditar.setLayout(btnEditarLayout);
        btnEditarLayout.setHorizontalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEditarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        btnEditarLayout.setVerticalGroup(
            btnEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEditarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator7)
                                    .addComponent(jSeparator6)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtDireccion)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lblcedula))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(txtApellido1)
                            .addComponent(txtSegundoNombre)
                            .addComponent(txtPrimerNombre)
                            .addComponent(txtCedulaBuscado)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3)
                            .addComponent(jSeparator4)
                            .addComponent(txtApellido2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator5))))
                .addGap(48, 48, 48))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(445, 445, 445))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcedula)
                    .addComponent(txtCedulaBuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDia))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 720, 530));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        bg.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 120, 500));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        bg.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 120, 500));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 620, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        jLabel17.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel17.setText("Datos del empleado");
        bg.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, 40));

        jLabel18.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel18.setText("___________________________");
        bg.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 20));

        javax.swing.GroupLayout jPanelEmpleadosLayout = new javax.swing.GroupLayout(jPanelEmpleados);
        jPanelEmpleados.setLayout(jPanelEmpleadosLayout);
        jPanelEmpleadosLayout.setHorizontalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmpleadosLayout.setVerticalGroup(
            jPanelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelPrincipal.add(jPanelEmpleados, "jPanelEmpleados");

        bg1.setBackground(new java.awt.Color(255, 255, 255));
        bg1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, 50, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/favicon.png"))); // NOI18N
        bg1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 50, 50));

        jLabel21.setFont(new java.awt.Font("Roboto Medium", 1, 36)); // NOI18N
        jLabel21.setText("Datos del Usuario");
        jLabel21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bg1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 336, 63));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        bg1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 370, 20));

        jLabel22.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel22.setText("User ID");

        jLabel23.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel23.setText("Nombre");

        jLabel24.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel24.setText("Apellido");

        jLabel25.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel25.setText("Contraseña");

        jLabel26.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel26.setText("Cédula");

        jLabel27.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel27.setText("Dirección");

        txtUsuarioID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioIDActionPerformed(evt);
            }
        });

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(51, 161, 214));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCrearUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearUsuario.setText("Crear usuario");
        btnCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCancelarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        cbAnioUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "1997", "1998", "1999", "2000", "2001", "2002", "2003", " " }));

        cbMesUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbDiaUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel31.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel31.setText("Fecha ingreso");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbAnioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbMesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbDiaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaUsuario)
                            .addComponent(txtApellidoUsuario)
                            .addComponent(txtNombreUsuario)
                            .addComponent(txtUsuarioID)
                            .addComponent(txtPasswordUsuario)
                            .addComponent(txtDireccionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))))
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(txtUsuarioID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23))
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel24))
                    .addComponent(txtApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel25))
                    .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel26))
                    .addComponent(txtCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel27))
                    .addComponent(txtDireccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMesUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDiaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAnioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        this.setResizable(false);

        bg1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 530, 570));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        bg1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 220, 620));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        bg1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 640));

        javax.swing.GroupLayout jPanelCrearUsuarioLayout = new javax.swing.GroupLayout(jPanelCrearUsuario);
        jPanelCrearUsuario.setLayout(jPanelCrearUsuarioLayout);
        jPanelCrearUsuarioLayout.setHorizontalGroup(
            jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCrearUsuarioLayout.setVerticalGroup(
            jPanelCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelPrincipal.add(jPanelCrearUsuario, "jPanelCrearUsuarios");

        jPanelPlanilla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("CALCULO DE PLANILLA");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 21, -1, -1));

        jbteliminar.setBackground(new java.awt.Color(153, 255, 255));
        jbteliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbteliminar.setText("- Eliminar Empleado");
        jbteliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbteliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbteliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbteliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 64, 131, 30));

        jbtadicionar.setBackground(new java.awt.Color(153, 255, 255));
        jbtadicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbtadicionar.setText("+ Adicionar Empleado");
        jbtadicionar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtadicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtadicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 64, 142, 30));

        tblplanilla.setBackground(java.awt.SystemColor.control);
        tblplanilla.setForeground(new java.awt.Color(153, 153, 0));
        tblplanilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "  CEDULA", " NOMBRE 1", " NOMBRE 2", " APELLIDO 1", " APELLIDO 2", "      HT", "     SxH", "SALARIO BRUTO ", "       SS", "       SE", "SALARIO NETO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblplanilla.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblplanilla);
        tblplanilla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblplanilla.getColumnModel().getColumnCount() > 0) {
            tblplanilla.getColumnModel().getColumn(9).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 112, 885, 277));

        jbtnactuali.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnactuali.setText("Actualizar");
        jbtnactuali.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnactuali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnactualiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnactuali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, 30));

        labelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city_1.png"))); // NOI18N
        labelfondo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 370, 490));

        jLabel32.setFocusable(false);
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 490));

        labelfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city.png"))); // NOI18N
        labelfondo1.setLabelFor(labelfondo);
        labelfondo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelfondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 490));

        labelfondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city_1.png"))); // NOI18N
        labelfondo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelfondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 300, 490));

        labelfondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/city_1.png"))); // NOI18N
        labelfondo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelfondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 370, 490));

        jPanelPlanilla.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        PanelPrincipal.add(jPanelPlanilla, "PanelPlanilla");

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(102, 153, 255));

        jmCrearUsuario.setText("Crear Usuario");
        jmCrearUsuario.setEnabled(false);
        jmCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmCrearUsuarioMousePressed(evt);
            }
        });
        jMenuBar1.add(jmCrearUsuario);

        jmVerEmpleado.setText("Ver Empleado");
        jmVerEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmVerEmpleadoMousePressed(evt);
            }
        });
        jMenuBar1.add(jmVerEmpleado);

        jmCrearPlanilla.setText("Crear Planilla");
        jmCrearPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmCrearPlanillaMousePressed(evt);
            }
        });
        jMenuBar1.add(jmCrearPlanilla);

        jmSalir.setText("Salir");
        jmSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmSalirMousePressed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (user.equals("admin")) {
            jmCrearUsuario.setEnabled(true);
        } else {
            jmCrearUsuario.setEnabled(false);
        }

    }//GEN-LAST:event_formWindowOpened

    private void jmSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSalirMousePressed
        // TODO add your handling code here:
        if (jmSalir.isSelected()) {
            System.exit(0);
        }
    }//GEN-LAST:event_jmSalirMousePressed

    private void txtCedulaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaBuscarActionPerformed

    private void cbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAnioActionPerformed

    private void txtUsuarioIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioIDActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed
    private void vaciarCamposUsuario(){
        txtUsuarioID.setText("");
        txtNombreUsuario.setText("");
        txtApellidoUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtCedulaUsuario.setText("");
        txtDireccionUsuario.setText("");
        cbAnioUsuario.setSelectedIndex(0);
        cbMesUsuario.setSelectedIndex(0);
        cbDiaUsuario.setSelectedIndex(0);
    }
    private void btnCrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseClicked
        // TODO add your handling code here:
        if(!txtUsuarioID.getText().isEmpty() && !txtNombreUsuario.getText().isEmpty() && !txtApellidoUsuario.getText().isEmpty() &&
                 !txtCedulaUsuario.getText().isEmpty() && !cbAnioUsuario.getSelectedItem().equals("")&& !cbMesUsuario.getSelectedItem().equals("") 
                && !cbDiaUsuario.getSelectedItem().equals("") && txtPasswordUsuario.getPassword().length != 0){
            
            Usuario usuario = new Usuario();
            ControlDAO control = new ControlDAO();
            String mensaje = "";
            usuario.setUsuario(String.valueOf(txtUsuarioID.getText()));
            usuario.setNombre(String.valueOf(txtNombreUsuario.getText()));
            usuario.setApellido(String.valueOf(txtApellidoUsuario.getText()));
            usuario.setPassword(String.valueOf(txtPasswordUsuario.getPassword()));
            usuario.setCedula(String.valueOf(txtCedulaUsuario.getText()));
            usuario.setDireccion(String.valueOf(txtDireccionUsuario.getText()));
            usuario.setFechaIngreso(String.valueOf(cbAnioUsuario.getSelectedItem() + "-"
                + cbMesUsuario.getSelectedItem() + "-" + cbDiaUsuario.getSelectedItem()));
            mensaje = control.insertarUsuario(usuario);
            if(!mensaje.equals("error")){
                JOptionPane.showMessageDialog(null,"Se agrego el usuario de la cédula " + mensaje +" correctmanete.");
                this.vaciarCamposUsuario();
            }else{
            JOptionPane.showMessageDialog(null,"No se pudo agregar el usuario.");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Hay campos vacios.");
        }
    }//GEN-LAST:event_btnCrearUsuarioMouseClicked

    private void btnCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMousePressed
        // TODO add your handling code here:
        this.vaciarCamposUsuario();
    }//GEN-LAST:event_btnCancelarMousePressed

    private void jmVerEmpleadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmVerEmpleadoMousePressed
        // TODO add your handling code here:
        if (jmVerEmpleado.isSelected()) {
            CardLayout jPanels = (CardLayout) PanelPrincipal.getLayout();
            jPanels.show(PanelPrincipal, "jPanelEmpleados");
        }
    }//GEN-LAST:event_jmVerEmpleadoMousePressed

    private void jmCrearUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCrearUsuarioMousePressed
        // TODO add your handling code here:
        if (jmCrearUsuario.isSelected()) {
            CardLayout jPanels = (CardLayout) PanelPrincipal.getLayout();
            jPanels.show(PanelPrincipal, "jPanelCrearUsuarios");
        }
    }//GEN-LAST:event_jmCrearUsuarioMousePressed

    private void jbteliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbteliminarActionPerformed
        // TODO add your handling code here:
//        Planilla obj = new Planilla();
//        int[] borrar = (tblplanilla.getSelectedRows());//Buscamos las filas que fueron seleccionados
//        if (borrar.length != 0) {//Verificamos que se haya seleccionado 1 por lo menos
//            int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro que deseas borrar " + borrar.length + " empleado?");
//            if (resp == 0) {
//                for (int i = 0; i < borrar.length; i++) {//Se repite el metodo borrar para borrar a los empleado de la planilla.
//                    String cedulaBorrar = String.valueOf(tblplanilla.getValueAt(borrar[i], 0));
//                    obj.eliminar(cedulaBorrar);//HAY QUE PONER SI DESEA ELIMINAR EL EMPLEADO SI O NO
//                }
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "No seleccionaste al empleado que deseas eliminar de la planilla");
//        }
    }//GEN-LAST:event_jbteliminarActionPerformed

    private void jbtadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtadicionarActionPerformed
        // TODO add your handling code here:
        frmEmpleadoPlanilla obj_añadir = new frmEmpleadoPlanilla();
        obj_añadir.setVisible(true);
    }//GEN-LAST:event_jbtadicionarActionPerformed

    private void jmCrearPlanillaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmCrearPlanillaMousePressed
        // TODO add your handling code here:
        if (jmCrearPlanilla.isSelected()) {
            CardLayout jPanels = (CardLayout) PanelPrincipal.getLayout();
            jPanels.show(PanelPrincipal, "PanelPlanilla");
        }

    }//GEN-LAST:event_jmCrearPlanillaMousePressed

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
        if (jPanel1.isFocusOwner()) {
            System.out.println("focus obtenido");
        }

    }//GEN-LAST:event_jPanel1FocusGained

    public void limpiartabla() {
        DefaultTableModel temp = (DefaultTableModel) tblplanilla.getModel();
        int filas = tblplanilla.getRowCount();

        for (int a = 0; filas > a; a++) {
            temp.removeRow(0);
        }
    }

    private void jbtnactualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnactualiActionPerformed
        // TODO add your handling code here://
//        ArrayList<controlador.Planilla> planilla = new ArrayList<>();
//        this.limpiartabla();//Primero se limpia la planilla
//        controlador.Planilla obj_dato = new controlador.Planilla();
//
//        if (obj_dato.ExistePlanilla()) {//Se verifica que ya exista un fichero planilla.
//            planilla = obj_dato.MostrarTodo();
//            DefaultTableModel model = (DefaultTableModel) tblplanilla.getModel();
//
//            for (int i = 0; i < planilla.size(); i++) {//Se agrega todo al arrayList para mostrarlo en la tabla
//
//                String[] arreglo = {planilla.get(i).getCedula(),
//                    planilla.get(i).getNombre(),
//                    planilla.get(i).getNombre2(),
//                    planilla.get(i).getApellido(),
//                    planilla.get(i).getApellido2(),
//                    String.valueOf(planilla.get(i).getHoratrabjada()),
//                    String.valueOf(planilla.get(i).getSphora()),
//                    String.valueOf(planilla.get(i).getSbruto()),
//                    String.valueOf(planilla.get(i).getSegsocial()),
//                    String.valueOf(planilla.get(i).getSegeducativo()),
//                    String.valueOf(planilla.get(i).getSNETO())};
//
//                model.addRow(arreglo);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Aún no se agrego ningún empleado a la planilla.");
//        }
    }//GEN-LAST:event_jbtnactualiActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEditarMouseClicked

    private void btnBuscarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEmpleadoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnBuscarEmpleadoMouseClicked

    private void labelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelBuscarMouseClicked
        // TODO add your handling code here:
        ControlDAO control = new ControlDAO();
        Empleado empleado = new Empleado();
        if (!txtCedulaBuscar.getText().isEmpty()) {
            empleado = control.seleccionarEmpleadoID(String.valueOf(txtCedulaBuscar.getText()));
            if (empleado != null) {
                labelEditarBoton.setEnabled(true);
                txtCedulaBuscado.setText(empleado.getCedula());
                txtCedulaBuscar.setEnabled(false);
                txtPrimerNombre.setText(empleado.getPrimerNombre());
                txtSegundoNombre.setText(empleado.getSegundoNombre());
                txtApellido1.setText(empleado.getPrimerApellido());
                txtApellido2.setText(empleado.getSegundoApellido());
                cbAnio.setSelectedItem(empleado.getFecha_nacimiento().substring(0, 4));
                cbMes.setSelectedItem(empleado.getFecha_nacimiento().substring(5, 7));
                String dia = empleado.getFecha_nacimiento().substring(8, 10);
                cbDia.setSelectedItem(dia);
                txtDireccion.setText(empleado.getDireccion());
                txtTelefono.setText(empleado.getTelefono());
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo encontrar al empleado que desea buscar.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No ingresaste la cédula del empleado que deseas buscar.");
        }
    }//GEN-LAST:event_labelBuscarMouseClicked

    private void labelNuevoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNuevoBotonMouseClicked
        // TODO add your handling code here:
        this.vaciarCampos();
        labelBuscar.setEnabled(false);
        labelNuevoBoton.setEnabled(false);
        txtCedulaBuscado.setEnabled(true);
        txtPrimerNombre.setEnabled(true);
        txtSegundoNombre.setEnabled(true);
        txtApellido1.setEnabled(true);
        txtApellido2.setEnabled(true);
        txtCedulaBuscar.setEnabled(false);
        cbAnio.setEnabled(true);
        cbMes.setEnabled(true);
        cbDia.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        labelGuardarBoton.setEnabled(true);
        labelEditarBoton.setEnabled(false);
    }//GEN-LAST:event_labelNuevoBotonMouseClicked

    private void labelEditarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEditarBotonMouseClicked
        // TODO add your handling code here:
        txtCedulaBuscado.setEnabled(false);
        txtPrimerNombre.setEnabled(true);
        txtSegundoNombre.setEnabled(true);
        txtApellido1.setEnabled(true);
        txtApellido2.setEnabled(true);
        cbAnio.setEnabled(true);
        cbMes.setEnabled(true);
        cbDia.setEnabled(true);
        txtDireccion.setEnabled(true);
        txtTelefono.setEnabled(true);
        txtCedulaBuscar.setEnabled(false);
        txtCedulaBuscar.setText("");
        labelBuscar.setEnabled(false);
        labelGuardarBoton.setEnabled(true);
        labelNuevoBoton.setEnabled(false);
        updateEmpleado = true;
        labelEditarBoton.setEnabled(false);
    }//GEN-LAST:event_labelEditarBotonMouseClicked

    private void vaciarCampos(){
        txtCedulaBuscar.setText("");
        txtCedulaBuscado.setText("");
        txtPrimerNombre.setText("");
        txtSegundoNombre.setText("");
        txtApellido1.setText("");
        txtApellido2.setText("");
        cbAnio.setSelectedIndex(0);
        cbMes.setSelectedIndex(0);
        cbDia.setSelectedIndex(0);
        txtDireccion.setText("");
        txtTelefono.setText("");
    }
    private void reiniciarCampos(){
        txtCedulaBuscar.setEnabled(true);
    txtCedulaBuscado.setEnabled(false);
        txtPrimerNombre.setEnabled(false);
        txtSegundoNombre.setEnabled(false);
        txtApellido1.setEnabled(false);
        txtApellido2.setEnabled(false);
        cbAnio.setEnabled(false);
        cbMes.setEnabled(false);
        cbDia.setEnabled(false);
        txtDireccion.setEnabled(false);
        txtTelefono.setEnabled(false);
        labelNuevoBoton.setEnabled(true);
        labelEditarBoton.setEnabled(false);
        labelGuardarBoton.setEnabled(false);
        labelBuscar.setEnabled(true);
    }
       private boolean verificarCampos() {
        if (!txtCedulaBuscado.getText().isEmpty() && !txtPrimerNombre.getText().isEmpty() && !txtSegundoNombre.getText().isEmpty() && !txtApellido1.getText().isEmpty()
                && !txtApellido2.getText().isEmpty() && !cbAnio.getSelectedItem().equals("") && !cbMes.getSelectedItem().equals("")
                && !cbDia.getSelectedItem().equals("") && !txtDireccion.getText().isEmpty() && !txtTelefono.getText().isEmpty()) {
            return false;
        } else {
            return true;
        }
    }
       private Empleado insertarCamposEmpleado(Empleado empleado) {

        empleado.setCedula(String.valueOf(txtCedulaBuscado.getText()));
        empleado.setPrimerNombre(String.valueOf(txtPrimerNombre.getText()));
        empleado.setSegundoNombre(String.valueOf(txtSegundoNombre.getText()));
        empleado.setPrimerApellido(String.valueOf(txtApellido1.getText()));
        empleado.setSegundoApellido(String.valueOf(txtApellido2.getText()));
        empleado.setFecha_nacimiento(String.valueOf(cbAnio.getSelectedItem() + "-"
                + cbMes.getSelectedItem() + "-" + cbDia.getSelectedItem()));
        empleado.setDireccion(String.valueOf(txtDireccion.getText()));
        empleado.setTelefono(String.valueOf(txtTelefono.getText()));
        return empleado;
    }
    private void labelGuardarBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelGuardarBotonMouseClicked
        // TODO add your handling code here:
        ControlDAO control = new ControlDAO();
        Empleado empleado = new Empleado();
        String mensaje ="";
        if (updateEmpleado != true) {
            if (!this.verificarCampos()) {
                empleado = this.insertarCamposEmpleado(empleado);
                mensaje = control.insertarEmpleado(empleado);
                if(!mensaje.equals("error")){
                    this.vaciarCampos();
                    JOptionPane.showMessageDialog(null, "Se agrego el empleado con la cédula " + mensaje+ " correctamente.");
                    labelNuevoBoton.setEnabled(true);
                    labelBuscar.setEnabled(true);
                    this.reiniciarCampos();
                }else{
                    JOptionPane.showMessageDialog(null, "Ya existe un empleado con esa cédula.");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Hay campos vacios.");
            }
        } else {
            updateEmpleado = false;//Regresamos la variable updateEmpleado a falso porque se quedaría en true y
                                   // estaría siempre actualizando en lugar de guardar cuando solo se quiere guardar
            if (!this.verificarCampos()) {
                empleado = this.insertarCamposEmpleado(empleado);
                mensaje = control.actualizarEmpleado(empleado);
                if(!mensaje.equals("error")){
                    this.vaciarCampos();
                    JOptionPane.showMessageDialog(null, "Se actualizo el empleado con la cédula " + mensaje+ " correctamente.");
                    this.reiniciarCampos();
                }else{
                    JOptionPane.showMessageDialog(null, "Hubo un problema al intentar actualizar el empleado.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Hay campos vacios.");
            }
        }
    }//GEN-LAST:event_labelGuardarBotonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel btnBuscarEmpleado;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnCrearUsuario;
    private javax.swing.JPanel btnEditar;
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JPanel btnNuevo;
    private javax.swing.JComboBox<String> cbAnio;
    private javax.swing.JComboBox<String> cbAnioUsuario;
    private javax.swing.JComboBox<String> cbDia;
    private javax.swing.JComboBox<String> cbDiaUsuario;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbMesUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelCrearUsuario;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelPlanilla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JButton jbtadicionar;
    private javax.swing.JButton jbteliminar;
    private javax.swing.JButton jbtnactuali;
    private javax.swing.JMenu jmCrearPlanilla;
    private javax.swing.JMenu jmCrearUsuario;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenu jmVerEmpleado;
    private javax.swing.JLabel labelBuscar;
    private javax.swing.JLabel labelEditarBoton;
    private javax.swing.JLabel labelGuardarBoton;
    private javax.swing.JLabel labelNuevoBoton;
    private javax.swing.JLabel labelfondo;
    private javax.swing.JLabel labelfondo1;
    private javax.swing.JLabel labelfondo2;
    private javax.swing.JLabel labelfondo3;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JTable tblplanilla;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtApellidoUsuario;
    private javax.swing.JTextField txtCedulaBuscado;
    private javax.swing.JTextField txtCedulaBuscar;
    private javax.swing.JTextField txtCedulaUsuario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccionUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txtPasswordUsuario;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUsuarioID;
    // End of variables declaration//GEN-END:variables
}
